/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bbcbb9",
        "on-secondary-fixed-variant": "#005047",
        "secondary-fixed": "#a8f0e3",
        "tertiary": "#006b5f",
        "background": "#f7f9fc",
        "primary-fixed-dim": "#3de273",
        "surface-container-highest": "#e0e3e6",
        "primary": "#006d2f",
        "on-surface-variant": "#3c4a3d",
        "on-tertiary-fixed-variant": "#005047",
        "on-background": "#191c1e",
        "tertiary-container": "#63c9b9",
        "on-error": "#ffffff",
        "on-primary-container": "#005523",
        "inverse-primary": "#3de273",
        "on-secondary-fixed": "#00201c",
        "primary-container": "#25d366",
        "surface-variant": "#e0e3e6",
        "surface-container-lowest": "#ffffff",
        "outline": "#6c7b6b",
        "surface-container-low": "#f2f4f7",
        "on-primary": "#ffffff",
        "secondary-container": "#a5ede0",
        "surface-dim": "#d8dadd",
        "on-tertiary-fixed": "#00201c",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#002109",
        "inverse-on-surface": "#eff1f4",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#66ff8e",
        "surface-bright": "#f7f9fc",
        "on-tertiary-container": "#005249",
        "surface-tint": "#006d2f",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#8cd4c7",
        "secondary": "#1c695f",
        "surface": "#f7f9fc",
        "on-secondary-container": "#226e63",
        "on-primary-fixed-variant": "#005322",
        "tertiary-fixed": "#8ff4e3",
        "tertiary-fixed-dim": "#72d8c8",
        "on-surface": "#191c1e",
        "surface-container": "#eceef1",
        "error": "#ba1a1a"
      },
      spacing: {
        "sidebar-width": "280px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
